name: Generate Docs

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  filter:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter jobs
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            test:
              - 'openapi/default.yml'
            index:
              - 'database/create_tables.sql'
    outputs:
      test: ${{ steps.filter.outputs.test }}
      index: ${{ steps.filter.outputs.index }}

  docs:
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test step
        if: needs.filter.outputs.test == 'true'
        run: |
          echo "do step test."

      - name: index step
        if: needs.filter.outputs.index == 'true'
        run: |
          echo "do index test."

      - name: Commit & Push
        run: |
          date > date.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "create file."
          git push
